//
//  PDFGenerator.swift
//  Papir
//
//  Created by Mykyta Kaisenberg on 2026-05-19.
//

import UIKit
import PDFKit

enum PDFLanguage: String, CaseIterable, Identifiable {
    case english
    case ukrainian
    case russian
    
    var id: String { rawValue }
    
    var displayName: String {
        switch self {
        case .english:   return "English"
        case .ukrainian: return "Українська"
        case .russian:   return "Русский"
        }
    }
    
    var flag: String {
        switch self {
        case .english:   return "🇬🇧"
        case .ukrainian: return "🇺🇦"
        case .russian:   return "🇷🇺"
        }
    }
    
    var title: String {
        switch self {
        case .english:   return "INVOICE"
        case .ukrainian: return "НАКЛАДНА"
        case .russian:   return "НАКЛАДНАЯ"
        }
    }
    
    var fromLabel: String {
        switch self {
        case .english:   return "FROM"
        case .ukrainian: return "ВІД"
        case .russian:   return "ОТ"
        }
    }
    
    var toLabel: String {
        switch self {
        case .english:   return "TO"
        case .ukrainian: return "ДЛЯ"
        case .russian:   return "ДЛЯ"
        }
    }
    
    var itemHeader: String {
        switch self {
        case .english:   return "ITEM"
        case .ukrainian: return "ТОВАР"
        case .russian:   return "ТОВАР"
        }
    }
    
    var qtyHeader: String {
        switch self {
        case .english:   return "QTY"
        case .ukrainian: return "К-ТЬ"
        case .russian:   return "К-ВО"
        }
    }
    
    var priceHeader: String {
        switch self {
        case .english:   return "PRICE"
        case .ukrainian: return "ЦІНА"
        case .russian:   return "ЦЕНА"
        }
    }
    
    var totalHeader: String {
        switch self {
        case .english:   return "TOTAL"
        case .ukrainian: return "СУМА"
        case .russian:   return "СУММА"
        }
    }
    
    var totalLabel: String {
        switch self {
        case .english:   return "TOTAL"
        case .ukrainian: return "УСЬОГО"
        case .russian:   return "ИТОГО"
        }
    }
    
    var footerText: String {
        switch self {
        case .english:   return "GENERATED BY PAPIR"
        case .ukrainian: return "СТВОРЕНО У PAPIR"
        case .russian:   return "СОЗДАНО В PAPIR"
        }
    }
    
    var dateLocale: Locale {
        switch self {
        case .english:   return Locale(identifier: "en_US")
        case .ukrainian: return Locale(identifier: "uk_UA")
        case .russian:   return Locale(identifier: "ru_RU")
        }
    }
}

struct PDFGenerator {
    
    // A4 in points: 595.2 × 841.8 (at 72 DPI)
    static let a4Size = CGSize(width: 595.2, height: 841.8)
    static let margin: CGFloat = 40
    static let fontScale: CGFloat = 1.05
    
    static func generate(for invoice: Invoice, language: PDFLanguage = .english) -> Data {
        let pageRect = CGRect(origin: .zero, size: a4Size)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        
        return renderer.pdfData { context in
            var cursorY: CGFloat = margin
            context.beginPage()
            
            cursorY = drawHeader(invoice: invoice, language: language, startY: cursorY, pageWidth: pageRect.width)
            cursorY += 20
            
            cursorY = drawParties(invoice: invoice, language: language, startY: cursorY, pageWidth: pageRect.width)
            cursorY += 24
            
            cursorY = drawTableHeader(language: language, startY: cursorY, pageWidth: pageRect.width)
            
            for (index, item) in invoice.items.enumerated() {
                if cursorY > pageRect.height - margin - 80 {
                    context.beginPage()
                    cursorY = margin
                    cursorY = drawTableHeader(language: language, startY: cursorY, pageWidth: pageRect.width)
                }
                
                cursorY = drawTableRow(
                    index: index + 1,
                    item: item,
                    startY: cursorY,
                    pageWidth: pageRect.width
                )
            }
            
            cursorY += 16
            
            if cursorY > pageRect.height - margin - 80 {
                context.beginPage()
                cursorY = margin
            }
            cursorY = drawTotal(total: invoice.totalInvoicePrice, language: language, startY: cursorY, pageWidth: pageRect.width)
            
            drawFooter(language: language, pageRect: pageRect)
        }
    }
    
    private static func drawHeader(invoice: Invoice, language: PDFLanguage, startY: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 26 * fontScale, weight: .black),
            .foregroundColor: UIColor.black,
            .kern: 6
        ]
        
        language.title.draw(at: CGPoint(x: margin, y: startY), withAttributes: titleAttrs)
        
        let dateFormatter = DateFormatter()
        dateFormatter.locale = language.dateLocale
        dateFormatter.dateStyle = .long
        let dateText = dateFormatter.string(from: invoice.date)
        let dateAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 11 * fontScale, weight: .medium),
            .foregroundColor: UIColor.darkGray
        ]
        let dateSize = (dateText as NSString).size(withAttributes: dateAttrs)
        dateText.draw(
            at: CGPoint(x: pageWidth - margin - dateSize.width, y: startY + 10),
            withAttributes: dateAttrs
        )
        
        let titleHeight: CGFloat = 36
        
        let line = UIBezierPath()
        line.move(to: CGPoint(x: margin, y: startY + titleHeight + 8))
        line.addLine(to: CGPoint(x: pageWidth - margin, y: startY + titleHeight + 8))
        UIColor.black.setStroke()
        line.lineWidth = 1
        line.stroke()
        
        return startY + titleHeight + 12
    }
    
    private static func drawParties(invoice: Invoice, language: PDFLanguage, startY: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 8 * fontScale, weight: .regular),
            .foregroundColor: UIColor.gray,
            .kern: 2
        ]
        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 12 * fontScale, weight: .medium),
            .foregroundColor: UIColor.black
        ]
        
        let columnWidth = (pageWidth - margin * 2 - 20) / 2
        
        language.fromLabel.draw(at: CGPoint(x: margin, y: startY), withAttributes: labelAttrs)
        let senderText = invoice.sender.isEmpty ? "—" : invoice.sender
        senderText.draw(at: CGPoint(x: margin, y: startY + 14), withAttributes: valueAttrs)
        
        let toX = margin + columnWidth + 20
        language.toLabel.draw(at: CGPoint(x: toX, y: startY), withAttributes: labelAttrs)
        let receiverText = invoice.receiver.isEmpty ? "—" : invoice.receiver
        receiverText.draw(at: CGPoint(x: toX, y: startY + 14), withAttributes: valueAttrs)
        
        return startY + 34
    }
    
    private static func drawTableHeader(language: PDFLanguage, startY: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 8 * fontScale, weight: .bold),
            .foregroundColor: UIColor.gray,
            .kern: 1.5
        ]
        
        let contentWidth = pageWidth - margin * 2
        let cols = columnLayout(contentWidth: contentWidth)
        
        "#".draw(at: CGPoint(x: margin, y: startY), withAttributes: attrs)
        language.itemHeader.draw(at: CGPoint(x: margin + cols.indexW, y: startY), withAttributes: attrs)
        
        let qtySize = (language.qtyHeader as NSString).size(withAttributes: attrs)
        language.qtyHeader.draw(
            at: CGPoint(x: margin + cols.indexW + cols.nameW + (cols.qtyW - qtySize.width) / 2, y: startY),
            withAttributes: attrs
        )
        
        let priceSize = (language.priceHeader as NSString).size(withAttributes: attrs)
        language.priceHeader.draw(
            at: CGPoint(x: margin + cols.indexW + cols.nameW + cols.qtyW + (cols.priceW - priceSize.width) / 2, y: startY),
            withAttributes: attrs
        )
        
        let totalSize = (language.totalHeader as NSString).size(withAttributes: attrs)
        language.totalHeader.draw(
            at: CGPoint(x: pageWidth - margin - totalSize.width, y: startY),
            withAttributes: attrs
        )
        
        let line = UIBezierPath()
        line.move(to: CGPoint(x: margin, y: startY + 16))
        line.addLine(to: CGPoint(x: pageWidth - margin, y: startY + 16))
        UIColor.lightGray.setStroke()
        line.lineWidth = 0.5
        line.stroke()
        
        return startY + 24
    }
    
    private static func drawTableRow(index: Int, item: ItemRow, startY: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let valueAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 11 * fontScale, weight: .regular),
            .foregroundColor: UIColor.black
        ]
        let nameAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 11 * fontScale, weight: .medium),
            .foregroundColor: UIColor.black
        ]
        let colorAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 8 * fontScale, weight: .regular),
            .foregroundColor: UIColor.darkGray
        ]
        let totalAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 11 * fontScale, weight: .semibold),
            .foregroundColor: UIColor.black
        ]
        
        let contentWidth = pageWidth - margin * 2
        let cols = columnLayout(contentWidth: contentWidth)
        
        "\(index)".draw(at: CGPoint(x: margin, y: startY), withAttributes: valueAttrs)
        
        item.name.draw(at: CGPoint(x: margin + cols.indexW, y: startY), withAttributes: nameAttrs)
        
        var nextRowOffset: CGFloat = 18
        if !item.colors.isEmpty {
            let colorsText = item.colors.joined(separator: " · ")
            colorsText.draw(
                at: CGPoint(x: margin + cols.indexW, y: startY + 14),
                withAttributes: colorAttrs
            )
            nextRowOffset = 30
        }
        
        let qtyText = "\(item.unitCount) × \(item.itemsPerUnit)"
        let qtySize = (qtyText as NSString).size(withAttributes: valueAttrs)
        qtyText.draw(
            at: CGPoint(x: margin + cols.indexW + cols.nameW + (cols.qtyW - qtySize.width) / 2, y: startY),
            withAttributes: valueAttrs
        )
        
        let priceText = formatNumber(item.price)
        let priceSize = (priceText as NSString).size(withAttributes: valueAttrs)
        priceText.draw(
            at: CGPoint(x: margin + cols.indexW + cols.nameW + cols.qtyW + (cols.priceW - priceSize.width) / 2, y: startY),
            withAttributes: valueAttrs
        )
        
        let lineTotal = formatNumber(item.totalForItem)
        let lineTotalSize = (lineTotal as NSString).size(withAttributes: totalAttrs)
        lineTotal.draw(
            at: CGPoint(x: pageWidth - margin - lineTotalSize.width, y: startY),
            withAttributes: totalAttrs
        )
        
        return startY + nextRowOffset
    }
    
    private static func drawTotal(total: Double, language: PDFLanguage, startY: CGFloat, pageWidth: CGFloat) -> CGFloat {
        let line = UIBezierPath()
        line.move(to: CGPoint(x: margin, y: startY))
        line.addLine(to: CGPoint(x: pageWidth - margin, y: startY))
        UIColor.black.setStroke()
        line.lineWidth = 1
        line.stroke()
        
        let labelAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 10 * fontScale, weight: .bold),
            .foregroundColor: UIColor.gray,
            .kern: 4
        ]
        let totalAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 22 * fontScale, weight: .bold),
            .foregroundColor: UIColor.black
        ]
        
        language.totalLabel.draw(at: CGPoint(x: margin, y: startY + 16), withAttributes: labelAttrs)
        
        let totalText = "\(formatNumber(total)) ₴"
        let totalSize = (totalText as NSString).size(withAttributes: totalAttrs)
        totalText.draw(
            at: CGPoint(x: pageWidth - margin - totalSize.width, y: startY + 12),
            withAttributes: totalAttrs
        )
        
        return startY + 50
    }
    
    private static func drawFooter(language: PDFLanguage, pageRect: CGRect) {
        let footerAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.monospacedSystemFont(ofSize: 7, weight: .regular),
            .foregroundColor: UIColor.lightGray,
            .kern: 2
        ]
        let footerSize = (language.footerText as NSString).size(withAttributes: footerAttrs)
        language.footerText.draw(
            at: CGPoint(
                x: (pageRect.width - footerSize.width) / 2,
                y: pageRect.height - margin / 2
            ),
            withAttributes: footerAttrs
        )
    }
    
    
    private struct ColumnLayout {
        let indexW: CGFloat
        let nameW: CGFloat
        let qtyW: CGFloat
        let priceW: CGFloat
        let totalW: CGFloat
    }
    
    private static func columnLayout(contentWidth: CGFloat) -> ColumnLayout {
        let indexW: CGFloat = 30
        let totalW: CGFloat = 90
        let qtyW: CGFloat = 80
        let priceW: CGFloat = 70
        let nameW = contentWidth - indexW - qtyW - priceW - totalW
        return ColumnLayout(indexW: indexW, nameW: nameW, qtyW: qtyW, priceW: priceW, totalW: totalW)
    }
    
    private static func formatNumber(_ value: Double) -> String {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        f.groupingSeparator = ","
        f.minimumFractionDigits = 0
        f.maximumFractionDigits = 2
        return f.string(from: NSNumber(value: value)) ?? "\(value)"
    }
}
